version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t $DOCKER_USER/pokemongo-json-pokedex .
      - run: docker run -ti $DOCKER_USER/pokemongo-json-pokedex start
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -t $DOCKER_USER/pokemongo-json-pokedex .
      - run: docker run -ti $DOCKER_USER/pokemongo-json-pokedex test

  npm_deploy:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npm run semantic-release || true

  docker_deploy:
    machine: true
    steps:
      - checkout
      # with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/pokemongo-json-pokedex:$CIRCLE_TAG .

      - run: docker tag $DOCKER_USER/pokemongo-json-pokedex:$CIRCLE_TAG $DOCKER_USER/pokemongo-json-pokedex:latest
      # deploy the image
      - run: docker push $DOCKER_USER/pokemongo-json-pokedex:$CIRCLE_TAG
      - run: docker push $DOCKER_USER/pokemongo-json-pokedex:latest


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test
      - npm_deploy:
          requires:
            - build
            - test
      - docker_deploy:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
